development:
  adapter: postgresql
  encoding: unicode
  database: inteligov_dev
  host: localhost
  pool: 5
  username: jhonnatan
  password: 'kakaroto#123#'

test:
  adapter: postgresql
  encoding: unicode
  database: inteligov_test
  host: localhost
  pool: 5
  username: jhonnatan
  password: 'kakaroto#123#'