development:
  adapter: postgresql
  encoding: unicode
  database: inteligov_dev
  host: localhost
  pool: 5
  username: jhonnatan
  password: 'kakaroto#123#'

production:
  adapter: postgresql
  encoding: unicode
  database: inteligov_prod
  host: localhost
  pool: 5
  username: jhonnatan
  password: 'kakaroto#123#'